### ISSUE TITLE
自动轮播不能循环

### ISSUE THREAD

**Issue by pigpigever** [davidlin88/vue-music#1]
请问遇过这个问题吗？就是**slider**在自动轮播的时候只进行一轮，我把阁下的代码复制过去也是这样。。

**Comment by recallwolf** [comment]
正好遇到这个问题了
https://ustbhuangyi.github.io/better-scroll/doc/zh-hans/api-specific.html#nexttime-easing
https://github.com/ustbhuangyi/better-scroll/blob/master/example/components/slide/slide.vue
看better-scroll的官方文档 把 `this.slider.goToPage(pageIndex, 0, 400)` 改成`this.slider.next(400)`

**Comment by pigpigever** [comment]
今天才看到，等会去试一下，多谢了。

**Comment by davidlin88** [comment]
感谢反馈!没收到github的issues提示,现在才看到,测试了下确实有问题~!ღ( ´･ᴗ･` )改成next是ok的
