### ISSUE TITLE
better-scroll只能降低版本解决吗？我调试了好久依然不行

### ISSUE THREAD

**Issue by simondengshuaihui** [davidlin88/vue-music#2]
better-scroll只能降低版本解决吗？我调试了好久依然不行

**Comment by davidlin88** [comment]
(。・＿・。)ﾉI’m sorry~
不好意思，现在才看到这个问题，github好像默认仓库issue没有消息提示 - -，现在已经开启了
这个问题建议尝试新版better-scroll，我记得有新的api了，还可以加better-scroll的官方交流群，会有人解答的哦，最主要的是多看它的文档，相信一定会有方案的~
